export const screenRouteNames = {
  InitOnboarding: "/onboarding/init",
  RegisterUserOnboarding: "/onboarding/registerUser",
  PermissionsOnboarding: "/onboarding/permissions",
  Home: "/home",
  ConfirmCreateIncident: "/incident/confirm",
  CallService: "/incident/create",
  Profile: "/profile",
  HealthInformation: "/profile/health",
  TemporaryInformation: "/profile/temporary",
  PersonalInformation: "/profile/personal",
  ContactList: "/profile/contacts",
  ContactDetail: "/profile/contacts/detail/:index/:contact",
  AddContactFromContactList: "/profile/contacts/addContactList",
  Test: "/test",
  TestConfirmCreateIncident: "/test/confirm",
  TestCallService: "/test/create",
  TestResultScreen: "/test/result",
};
